apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    secret.reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    spec:
      initContainers:
        - name: init-hosts
          image: bitnami/kubectl:latest
          command: ["bash", "-c", "HOSTALIAS_IP=$(kubectl get secret frontend-int1 -o jsonpath='{.data.HOSTALIAS_IP}' | base64 -d );  echo $(HOSTALIAS_HOSTNAME) $HOSTALIAS_IP >> /etc/hosts"]
          volumeMounts:
            - name: resolved-hosts
              mountPath: /etc/hosts
              subPath: hosts
      containers:
        - name: frontend
          image: dtsrhpdevscedacr.azurecr.io/secure-client-hub/msca-frontend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: frontend
            - secretRef:
                name: frontend
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-shared
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: resolved-hosts
              mountPath: /etc/hosts
              subPath: hosts
        - name: fluentd
          image: docker.io/fluentd
          args: [--config, /etc/fluentd.conf]
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: audit-logs
              mountPath: /logs
            - name: fluentd-conf
              mountPath: /etc/fluentd.conf
              subPath: fluentd.conf
      volumes:
        - name: fluentd-conf
          configMap:
            name: frontend-fluentd
        - name: resolved-hosts
          emptyDir: {}
