name: Build MSCA-Portal frontend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-frontend.yaml
      - frontend/**
  workflow_call: {}
  workflow_dispatch: {}

env:
  CI: true

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm clean-install
        working-directory: frontend/
      - run: npm run format:check
        working-directory: frontend/
      - run: npm run typecheck
        working-directory: frontend/
      - run: npm run lint:check
        working-directory: frontend/
      #- run: npm run test -- --coverage
      #  working-directory: frontend/
      #- run: npx playwright install chromium --with-deps
      #  working-directory: frontend/
      #- run: npm run test:e2e
      #  working-directory: frontend/
  build-frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend-changed == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm clean-install
        working-directory: frontend/
      - run: podman build --file containerfile .
        working-directory: frontend/
